services:
  backend:
    image: treasuremeasure/my-backend-image
    ports: "3000:3000"
    restart-policy: unless-stopped
  frontend:
    image: treasuremeasure/my-frontend-image
    ports: "5173:5173"
    restart: unless-stopped

networks:
  default: 
    driver: bridge

  

  