services:
  backend:
    image: treasuremeasure/go-backend-image
    ports: 
      - "3000:8081"
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/health || exit 1"]
      interval: 30s    
      timeout: 5s         
      start_period: 10s   
      retries: 3           
  frontend:
    image: treasuremeasure/my-vue-image
    ports: 
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s     
      timeout: 5s       
      start_period: 10s 
      retries: 3

networks:
  default: 
    driver: bridge

  

  